# Generated by Django 2.2.1 on 2019-05-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190513_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.RemoveField(
            model_name='client',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
        migrations.RemoveField(
            model_name='client',
            name='registered_date',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
