# Generated by Django 2.2.1 on 2019-05-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190513_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gym',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gym'),
        ),
    ]
